### ISSUE TITLE
Short code did't render

### ISSUE THREAD

**Issue by kovexal** [muuvmuuv/grav-plugin-adsense#8]
Hi my system details
Grav v1.3.1 
Admin v1.5.1
AdSense v1.1.1, 
Shortcode Core  v2.6.0

I've installed the plugin and try to have the adsense ads been shown instead of a shortcode. Without success. Every time I add 

'[adsense type="banner" direction="top" sandy="" class=""] [/adsense]` 

in the middle of my content I see the shortcode exactly in the same way in the browser 

![image](https://user-images.githubusercontent.com/30614978/28810148-8cf4168a-7688-11e7-9f97-1c7ae26a85c8.png)

Where did I miss something?

here is the adsens global conf

```
# Global plugin configurations

enabled: true             # Set to false to disable this plugin completely
sandbox: false            # Enables a demo mode for local purpose

# Default configurations for AdSense

adsense:
  options:
    type: "banner"        # Assets type (either "banner" or "fixed")
    direction: "top"      # Assets direction (either "left", "right", "top", "bottom")
    priority: -999        # Priority to add CSS or JS to Grav pipeline, bigger comes first
    pipeline: false       # Pipeline assets or not
    load: ""              # Load asset either asynchronously "async", deferred "defer" or normal ""
    resource: "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js" # AdSense script url

  data:
    client: "ca-pub-***************     # AdSense client
    slot: ************                      # AdSense slot
```
in the page itself I've added a local conf to the fronmatter
```
adsense:
  active: true
  type: "banner"
  direction: "top"
  slot: '******' #same as in global conf
```

thanks for your support
